stages:
  data_ingestion:
    cmd: python src/kidneyCtClassifier/pipeline/stage_01_data_ingestion.py
    deps:
      - src/kidneyCtClassifier/pipeline/stage_01_data_ingestion.py
      - config/config.yaml
    outs:
      - artifacts/data_ingestion/kidney-ct-scan-image
  model_preparation:
    cmd: python src/kidneyCtClassifier/pipeline/stage_02_model_preparation.py
    deps:
      - src/kidneyCtClassifier/pipeline/stage_02_model_preparation.py
      - config/config.yaml
    outs:
      - artifacts/prepare_base_model
  model_training:
    cmd: python src/kidneyCtClassifier/pipeline/stage_03_model_training.py
    deps:
      - src/kidneyCtClassifier/pipeline/stage_03_model_training.py
      - config/config.yaml
      - artifacts/data_ingestion/kidney-ct-scan-image
      - artifacts/prepare_base_model
    outs:
      - artifacts/training
    params:
      - BATCH_SIZE
      - N_EPOCHS
      - LR
  evaluation:
    cmd: python src/kidneyCtClassifier/pipeline/stage_04_mlflow_model_evaluation.py
    deps:
      - src/kidneyCtClassifier/pipeline/stage_04_mlflow_model_evaluation.py
      - config/config.yaml
      - artifacts/data_ingestion/kidney-ct-scan-image
      - artifacts/training/model.pth
    params:
      - BATCH_SIZE
    metrics:
      - scores.json:
          cache: false